"""add image urls to dishes and recipes

Revision ID: 865e558228cb
Revises: 01a1cbea4098
Create Date: 2023-11-18 17:31:54.152732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865e558228cb'
down_revision: Union[str, None] = '01a1cbea4098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_dishes', sa.Column('image_url', sa.String(length=256), nullable=True))
    op.add_column('t_recipes', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_recipes', 'image_url')
    op.drop_column('t_dishes', 'image_url')
    # ### end Alembic commands ###
